name: bus_bus
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.6.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  email_validator: ^3.0.0
  mysql1: ^0.20.0
  crypto: ^3.0.6
  intl: ^0.20.2
  http: ^1.3.0
  shared_preferences: ^2.2.2
  bcrypt: ^1.1.3
  flutter_dotenv: ^5.2.1
  image_picker: ^1.1.2
  google_maps_flutter: ^2.5.0
  flutter_map: ^8.0.0
  latlong2: ^0.9.1
  file_picker: ^9.0.1
  flutter_map_cancellable_tile_provider: ^3.1.0
  flutter_typeahead: ^5.2.0
  flutter_plugin_android_lifecycle: ^2.0.24

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
